### PR TITLE
Filter countries

### PR DESCRIPTION
**Pull request by muirurii**
Added filter by country functionality in the communities page

### CODE REVIEW

**Review by Collins87mbathi — APPROVED** [review]

**Comment by Collins87mbathi** [comment]
Hello muiruri. Please check your build i guess it has some error.

**Comment by Collins87mbathi** [comment]
@muirurii check your build it has some error thats why it can't be merged.

**Comment by muirurii** [comment]
@Collins87mbathi Found the bug, let me correct it.

**Review by ondiekelijah — APPROVED** [review]

**Comment by amwatah** [comment]
This PR   was closed  because we had  a major   change that discarded the changes made herein

**Pull request closed without merging**
